package io.mex.provision

import io.mex.data.Lab
import io.mex.data.LabTopology
import java.net.InetAddress
import java.net.ServerSocket
import java.security.SecureRandom
import java.util.Base64

/* ===================== lab plan ===================== */

/**
 * The expanded shape of a lab: every process, its replica-set membership, and which
 * services face the host. Pure; consumed by both the renderer and the bootstrap phases
 * so the compose file and the rs.initiate member lists can never disagree (PRV-RENDER-6).
 */
data class LabPlan(
    val project: String,
    val mongods: List<MongodSpec>,
    val mongosList: List<String>,
    val replicaSets: List<RsSpec>,
    /** Services that get a 127.0.0.1 host port, in stable order (PRV-RENDER-3). */
    val clientServices: List<String>,
)

data class MongodSpec(
    val name: String,
    val replSet: String?,
    val configSvr: Boolean = false,
    val shardSvr: Boolean = false,
)

data class RsSpec(val name: String, val members: List<String>, val configSvr: Boolean)

fun plan(lab: Lab): LabPlan {
    val project = "mex-lab-${lab.id8}"
    return when (val t = lab.topology) {
        is LabTopology.Standalone -> LabPlan(
            project = project,
            mongods = listOf(MongodSpec("rs-n1", replSet = null)),
            mongosList = emptyList(),
            replicaSets = emptyList(),
            clientServices = listOf("rs-n1"),
        )
        is LabTopology.ReplicaSet -> {
            val members = (1..t.members).map { "rs-n$it" }
            LabPlan(
                project = project,
                mongods = members.map { MongodSpec(it, replSet = "rs0") },
                mongosList = emptyList(),
                replicaSets = listOf(RsSpec("rs0", members, configSvr = false)),
                clientServices = members,
            )
        }
        is LabTopology.Sharded -> {
            val cfg = (1..t.configServers).map { "cfg-n$it" }
            val shards = (1..t.shards).map { s -> RsSpec("sh$s", (1..t.membersPerShard).map { "sh$s-n$it" }, configSvr = false) }
            val mongos = (1..t.mongos).map { "mongos-$it" }
            LabPlan(
                project = project,
                mongods = cfg.map { MongodSpec(it, replSet = "cfg", configSvr = true) } +
                    shards.flatMap { rs -> rs.members.map { MongodSpec(it, replSet = rs.name, shardSvr = true) } },
                mongosList = mongos,
                replicaSets = listOf(RsSpec("cfg", cfg, configSvr = true)) + shards,
                clientServices = mongos,
            )
        }
    }
}

/** Replica sets in labs use keyfile internal auth; a standalone only needs `--auth` (PRV-SEC-1/2). */
fun needsKeyfile(lab: Lab): Boolean = lab.auth && lab.topology !is LabTopology.Standalone

/* ===================== keyfile & ports ===================== */

/** 756 random bytes, base64 — the shape `openssl rand -base64 756` produces (PRV-SEC-2). */
fun generateKeyfile(): String {
    val bytes = ByteArray(756).also { SecureRandom().nextBytes(it) }
    return Base64.getMimeEncoder(76, byteArrayOf('\n'.code.toByte())).encodeToString(bytes) + "\n"
}

/**
 * Reserves one free ephemeral port per client-facing service by binding and releasing
 * (PRV-RENDER-3). All sockets are held open until every port is known, so the result
 * is collision-free within itself; a rare later bind race is retried at `up` time.
 */
fun allocatePorts(services: List<String>): Map<String, Int> {
    val loopback = InetAddress.getLoopbackAddress()
    val sockets = services.map { ServerSocket(0, 1, loopback) }
    try {
        return services.zip(sockets.map { it.localPort }).toMap()
    } finally {
        sockets.forEach { runCatching { it.close() } }
    }
}

/* ===================== compose rendering ===================== */

private const val KEYFILE_MOUNT = "./keyfile:/keyfile-src/keyfile:ro"

/**
 * Deterministic topology → compose.yaml (PRV-RENDER-5). The layout mirrors the proven
 * `testing/` rigs: internal port 27017, member specs by service name, mongosh-ping
 * healthchecks — plus lab labels, explicit 127.0.0.1 binds, and WiredTiger cache caps.
 */
fun renderCompose(lab: Lab, portMap: Map<String, Int>): String {
    val p = plan(lab)
    val keyfile = needsKeyfile(lab)
    val sb = StringBuilder()
    sb.appendLine("# Generated by Mongo Explorer v3 for lab \"${lab.name}\" (${lab.id}).")
    sb.appendLine("# The app owns this file — manual edits are overwritten.")
    sb.appendLine("name: ${p.project}")
    sb.appendLine()
    sb.appendLine("services:")

    for (m in p.mongods) {
        val flags = buildList {
            if (m.configSvr) add("--configsvr")
            if (m.shardSvr) add("--shardsvr")
            m.replSet?.let { add("--replSet $it") }
            add("--port 27017")
            add("--bind_ip_all")
            add("--wiredTigerCacheSizeGB 0.25")
            if (lab.auth && m.replSet == null) add("--auth")
            if (keyfile) add("--keyFile /run/mex/keyfile")
        }
        service(sb, lab, m.name, "mongod ${flags.joinToString(" ")}", keyfile, portMap[m.name], volume = true)
    }

    if (p.mongosList.isNotEmpty()) {
        val cfgRs = p.replicaSets.first { it.configSvr }
        val configdb = "${cfgRs.name}/" + cfgRs.members.joinToString(",") { "$it:27017" }
        for (name in p.mongosList) {
            val flags = buildList {
                add("--configdb $configdb")
                add("--port 27017")
                add("--bind_ip_all")
                if (keyfile) add("--keyFile /run/mex/keyfile")
            }
            service(sb, lab, name, "mongos ${flags.joinToString(" ")}", keyfile, portMap[name], volume = false)
        }
    }

    val volumes = p.mongods.map { "${it.name}-data" }
    sb.appendLine("volumes:")
    for (v in volumes) {
        sb.appendLine("  $v:")
        sb.appendLine("    labels:")
        sb.appendLine("      mex.lab.id: ${lab.id}")
    }
    sb.appendLine()
    sb.appendLine("networks:")
    sb.appendLine("  default:")
    sb.appendLine("    labels:")
    sb.appendLine("      mex.lab.id: ${lab.id}")
    return sb.toString()
}

private fun service(
    sb: StringBuilder,
    lab: Lab,
    name: String,
    command: String,
    keyfile: Boolean,
    hostPort: Int?,
    volume: Boolean,
) {
    sb.appendLine("  $name:")
    sb.appendLine("    image: mongo:${lab.mongoTag}")
    if (keyfile) {
        // The keyfile is staged inside the container so mongod's ownership/permission
        // checks pass regardless of host-side bind-mount semantics (PRV-SEC-2). The
        // official image entrypoint then drops privileges as usual.
        val stage = "mkdir -p /run/mex && cp /keyfile-src/keyfile /run/mex/keyfile && " +
            "chmod 400 /run/mex/keyfile && chown mongodb:mongodb /run/mex/keyfile && " +
            "exec docker-entrypoint.sh $command"
        sb.appendLine("    entrypoint: [\"bash\", \"-c\", \"$stage\"]")
    } else {
        sb.appendLine("    command: $command")
    }
    val mounts = buildList {
        if (volume) add("$name-data:/data/db")
        if (keyfile) add(KEYFILE_MOUNT)
    }
    if (hostPort != null) sb.appendLine("    ports: [\"127.0.0.1:$hostPort:27017\"]")
    if (mounts.isNotEmpty()) sb.appendLine("    volumes: [${mounts.joinToString(", ")}]")
    sb.appendLine("    labels: [\"mex.lab.id=${lab.id}\"]")
    sb.appendLine("    healthcheck:")
    sb.appendLine("      test: [\"CMD\", \"mongosh\", \"--quiet\", \"--eval\", \"db.adminCommand('ping').ok\"]")
    sb.appendLine("      interval: 5s")
    sb.appendLine("      timeout: 3s")
    sb.appendLine("      retries: 20")
    sb.appendLine()
}
